"""adiciona itens no pedido

Revision ID: 0d5ff42f6686
Revises: a6c9cc12c2d1
Create Date: 2025-10-30 09:25:42.172359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d5ff42f6686'
down_revision: Union[str, Sequence[str], None] = 'a6c9cc12c2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
